version: '3.9'
services:

#####
## Kanban stack
#####

  kanban-postgres:
    image: postgres:9.6-alpine
    container_name: kanban-postgres
    networks:
      mindspace_kanban-stack:
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban

  kanban-app:
    image: rquinzio/kanban-stack-app
    container_name: kanban-app
    networks:
      mindspace_kanban-stack:
    environment:
      - DB_SERVER=kanban-postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8080

  kanban-ui:
    image: rquinzio/kanban-stack-ui
    container_name: kanban-ui
    networks:
      mindspace_kanban-stack:
    ports:
      - 4000:80

######
## Whiteboard
######

  whiteboard-app:
    image: lovasoa/wbo
    container_name: whiteboard-ui
    networks:
      mindspace_whiteboard:
    ports:
      - 4100:80

######
## Mindmaps
######

  mindmaps-app:
    image: rquinzio/mindmaps-docker
    container_name: mindmaps-ui
    networks:
      mindspace_mindmaps:
    ports:
      - 4200:80

volumes:
  kanban-data:

networks:
  mindspace_kanban-stack:
  mindspace_whiteboard:
  mindspace_mindmaps: